export const BRAND_SUCCESS = "BRAND_SUCCESS";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const GET_FAILURE = "GET_FAILURE";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const PROFILE_LOADED = "PROFILE_LOADED";
